languageCode = "en-us"
title = "~vsmoraes"
baseURL = "https://vsmoraes.github.io/"
publishDir = "docs"
theme = "hugo-theme-nix"
[params]
  GithubID = "vsmoraes"
  TwitterID = "vsmoraes"
  LinkedInID = "vsmoraes"
  Name = "Vinicius"
  HeaderUsername = "vinicius"
  HeaderHostname = "vsmoraes.com"
  Email = "vinicius@vsmoraes.com"
  About = "Hi! I'm Vinicius and this is my website. I am a developer, gamer and a curious man."
  ProfilePicture = "https://scontent.fgru5-1.fna.fbcdn.net/v/t1.0-9/17499552_1697509753596576_1435938405298557175_n.jpg?oh=bc57acdca0d05d19220b803f40d870ca&oe=595E29D8"
